"""
LLM-Powered Multi-Hop Reasoning Module
Uses LLM to dynamically decompose questions instead of regex patterns
"""
from typing import List, Dict
from dataclasses import dataclass
import json
import logging
from groq import Groq
from graphrag.config import settings

logger = logging.getLogger(__name__)


@dataclass
class LLMReasoningStep:
    """Single reasoning step generated by LLM"""
    step_number: int
    step_type: str  # "retrieve", "infer", "compare", "aggregate"
    query: str
    reasoning: str
    confidence: float


@dataclass
class LLMMultiHopReasoning:
    """Complete LLM-generated reasoning chain"""
    original_question: str
    is_complex: bool
    complexity_reason: str
    sub_questions: List[str]
    reasoning_steps: List[LLMReasoningStep]
    final_synthesis: str
    total_confidence: float


class LLMMultiHopReasoner:
    """
    LLM-powered multi-hop reasoning - No regex patterns!
    
    Advantages:
    - Understands question complexity naturally
    - Generates sub-questions dynamically
    - Adapts to any question type
    - No pattern maintenance needed
    """
    
    def __init__(self, llm_client=None, retriever=None):
        self.llm_client = llm_client or Groq(api_key=settings.groq_api_key)
        self.model = settings.groq_model
        self.retriever = retriever
    
    def analyze_question_complexity(self, question: str) -> Dict:
        """
        Use LLM to determine if question is complex
        
        No regex patterns - LLM understands naturally!
        """
        
        prompt = f"""Analyze this question for complexity:

Question: "{question}"

Determine:
1. Is this a complex question requiring multiple steps? (yes/no)
2. Why is it complex or simple?
3. How many reasoning steps would be needed? (1-5)

Respond with JSON:
{{
  "is_complex": true/false,
  "complexity_reason": "explanation",
  "estimated_steps": number,
  "question_type": "simple|comparison|procedural|hypothetical|multi-part"
}}

Examples:
- "What are requirements?" → simple (1 step)
- "How can X become Y?" → complex (3-4 steps: requirements, procedures, eligibility)
- "What's difference between X and Y?" → complex (3 steps: define X, define Y, compare)
- "If I don't have X, can I still Y?" → complex (2-3 steps: check requirements, analyze alternatives)

Analyze: "{question}"

Respond ONLY with valid JSON."""

        try:
            response = self.llm_client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a question complexity analyzer. Always respond with valid JSON."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3,
                max_tokens=300,
                response_format={"type": "json_object"}
            )
            
            analysis = json.loads(response.choices[0].message.content)
            logger.info(f"Question complexity: {analysis.get('is_complex')} - {analysis.get('complexity_reason')}")
            
            return analysis
        
        except Exception as e:
            logger.error(f"Complexity analysis failed: {e}")
            return {
                "is_complex": False,
                "complexity_reason": "Analysis failed",
                "estimated_steps": 1,
                "question_type": "simple"
            }
    
    def decompose_question_with_llm(self, question: str) -> List[str]:
        """
        Use LLM to decompose complex question into sub-questions
        
        No hardcoded patterns - LLM generates dynamically!
        """
        
        prompt = f"""Decompose this complex question into simpler sub-questions:

Question: "{question}"

Generate 2-5 sub-questions that, when answered together, fully address the original question.

Rules:
- Each sub-question should be answerable independently
- Sub-questions should be in logical order
- Keep the same language as the original
- Be specific and clear

Example for "How can a doctor become a university lecturer?":
{{
  "sub_questions": [
    "What are the requirements to become a university lecturer?",
    "What qualifications does a doctor have?",
    "What additional steps must a doctor take?",
    "What is the application procedure?"
  ]
}}

Example for "What's the difference between X and Y?":
{{
  "sub_questions": [
    "What is X and what are its characteristics?",
    "What is Y and what are its characteristics?",
    "How do X and Y compare?"
  ]
}}

Decompose: "{question}"

Respond ONLY with valid JSON."""

        try:
            response = self.llm_client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a question decomposition expert. Always respond with valid JSON."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.5,
                max_tokens=500,
                response_format={"type": "json_object"}
            )
            
            decomposition = json.loads(response.choices[0].message.content)
            sub_questions = decomposition.get("sub_questions", [question])
            
            logger.info(f"Decomposed into {len(sub_questions)} sub-questions")
            
            return sub_questions
        
        except Exception as e:
            logger.error(f"Question decomposition failed: {e}")
            return [question]  # Fallback to original
    
    def perform_llm_multi_hop_reasoning(self, question: str) -> LLMMultiHopReasoning:
        """
        Perform complete multi-hop reasoning using LLM
        
        Fully dynamic - no regex, no hardcoded patterns!
        """
        
        # Step 1: Analyze complexity
        complexity_analysis = self.analyze_question_complexity(question)
        is_complex = complexity_analysis.get("is_complex", False)
        
        if not is_complex:
            # Simple question - single step
            step = LLMReasoningStep(
                step_number=1,
                step_type="retrieve",
                query=question,
                reasoning="Direct retrieval for simple question",
                confidence=0.9
            )
            
            return LLMMultiHopReasoning(
                original_question=question,
                is_complex=False,
                complexity_reason=complexity_analysis.get("complexity_reason", "Simple question"),
                sub_questions=[question],
                reasoning_steps=[step],
                final_synthesis=f"Direct answer to: {question}",
                total_confidence=0.9
            )
        
        # Step 2: Decompose into sub-questions
        sub_questions = self.decompose_question_with_llm(question)
        
        # Step 3: Create reasoning steps
        reasoning_steps = []
        
        for i, sub_q in enumerate(sub_questions, 1):
            step = LLMReasoningStep(
                step_number=i,
                step_type="retrieve" if i < len(sub_questions) else "aggregate",
                query=sub_q,
                reasoning=f"Step {i}: {sub_q}",
                confidence=0.8
            )
            reasoning_steps.append(step)
        
        # Step 4: Calculate confidence
        total_confidence = sum(s.confidence for s in reasoning_steps) / len(reasoning_steps)
        
        # Step 5: Generate synthesis
        synthesis = self._synthesize_with_llm(question, sub_questions)
        
        result = LLMMultiHopReasoning(
            original_question=question,
            is_complex=True,
            complexity_reason=complexity_analysis.get("complexity_reason", "Complex question"),
            sub_questions=sub_questions,
            reasoning_steps=reasoning_steps,
            final_synthesis=synthesis,
            total_confidence=total_confidence
        )
        
        logger.info(
            f"Multi-hop reasoning complete: {len(reasoning_steps)} steps, "
            f"confidence: {total_confidence:.2%}"
        )
        
        return result
    
    def _synthesize_with_llm(self, question: str, sub_questions: List[str]) -> str:
        """Use LLM to synthesize final answer structure"""
        
        prompt = f"""Given this complex question and its sub-questions, describe how to synthesize the final answer:

Original Question: "{question}"

Sub-questions:
{chr(10).join(f'{i}. {sq}' for i, sq in enumerate(sub_questions, 1))}

Provide a brief synthesis strategy (2-3 sentences) explaining how to combine the sub-answers.

Example: "First, gather the requirements from sub-question 1. Then, check the applicant's qualifications from sub-question 2. Finally, compare them and identify any gaps or additional steps needed."

Respond with plain text (no JSON)."""

        try:
            response = self.llm_client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are an answer synthesis expert."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.5,
                max_tokens=200
            )
            
            return response.choices[0].message.content.strip()
        
        except Exception as e:
            logger.error(f"Synthesis failed: {e}")
            return f"Combine answers from {len(sub_questions)} sub-questions to address: {question}"
    
    def format_reasoning_info(self, reasoning: LLMMultiHopReasoning) -> str:
        """Format reasoning information for display"""
        lines = []
        
        lines.append("🤖 **تحليل متعدد الخطوات بالذكاء الاصطناعي**\n")
        lines.append(f"❓ **السؤال**: {reasoning.original_question}\n")
        
        lines.append(f"🔍 **التعقيد**: {'معقد' if reasoning.is_complex else 'بسيط'}")
        lines.append(f"💡 **السبب**: {reasoning.complexity_reason}\n")
        
        if reasoning.is_complex:
            lines.append(f"📋 **الأسئلة الفرعية ({len(reasoning.sub_questions)}):**")
            for i, sq in enumerate(reasoning.sub_questions, 1):
                lines.append(f"  {i}. {sq}")
            lines.append("")
            
            lines.append(f"🔗 **خطوات التحليل ({len(reasoning.reasoning_steps)}):**")
            for step in reasoning.reasoning_steps:
                lines.append(f"  {step.step_number}. [{step.step_type}] {step.query[:60]}...")
            lines.append("")
            
            lines.append("📊 **استراتيجية التجميع:**")
            lines.append(f"  {reasoning.final_synthesis}\n")
        
        lines.append(f"✅ **الثقة الإجمالية**: {reasoning.total_confidence:.0%}")
        lines.append("✨ **تم التحليل باستخدام الذكاء الاصطناعي - لا أنماط regex!**")
        
        return "\n".join(lines)
